### ISSUE TITLE
Liens article précédent et suivant

### ISSUE THREAD

**Issue by ghislainguy** [samszo/open-edition#1]
Bonjour, 
Je bloque sur une boucle :
J'aimerais avoir des liens article précédent et suivant. (d'un même numéro)
Mais ça ne fonctionne pas sur toutes les pages.

```
<BOUCLE_precedent(ARTICLES){id_rubrique}{age_relatif>=0}{par date}{inverse}{1,1}>
<a href='#URL_ARTICLE'>#TITRE</a>
</BOUCLE_precedent>

<br>-<br>

<BOUCLE_suivant(ARTICLES){id_rubrique}{age_relatif<0}{par date}{0,1}>
<a href='#URL_ARTICLE'>#TITRE</a>
</BOUCLE_suivant>
```

Merci d'avance pour votre aide...

**Comment by samszo** [comment]
pour gérer ce problème j'ai : 
- ajouté le plugin suivant : http://contrib.spip.net/Criteres-precedent-et-suivant
- créé deux boucles cf. squelette article.html lignes 192->199
  https://github.com/samszo/open-edition/blob/master/squelettes/article.html#L192

**Comment by ghislainguy** [comment]
Merci, ça marche super !
