### ISSUE TITLE
Formulaire proposition : vérification

### ISSUE THREAD

**Issue by samszo** [samszo/open-edition#14]
Il faut faire des vérifications sur la saisie du formulaire : 
- champs obligatoires : 
  - domaine
  - revue
  - numéro
  - titre
  - auteur
  - ...
- nb des mot-clefs fr = nb des mots-clefs en
- ...

**Comment by ghislainguy** [comment]
J'ai changé la page de l'article : elle va chercher les domaines de la revue parente.
Plus besoin d'enregistrer les domaines dans les articles. ( ni les mots-clefs, ni le domaine principal )
On peut supprimer le champ extra "Domaine principal" **de l'article.** 
ça simplifie le formulaire de l'article, aussi.

**Comment by ghislainguy** [comment]
Je suis en train de mettre àjour le formulaire,
Après, j'aimerais savoir comment le formulaire enregistre les infos dans la base. Je ne trouve pas le fichier PHP qui fait les requêtes...

**Comment by ghislainguy** [comment]
ça fonctionne.
