### ISSUE TITLE
Ajout d'article

### ISSUE THREAD

**Issue by samszo** [samszo/open-edition#18]
Le formulaire d'ajout d'article passe par le choix d'une revue à partir de quoi on "calcule" le dernier numéro pour y ajouter l'article.
Est-ce qu'on est certain qu'il n'y aura qu'un seul numéro "en cours" ?
Est-ce que ce numéro sera le même pour l'anglais et le français ?

Je propose  un autre mode de fonctionnement : 
1. le rédacteur en chef crée un nouveau numéro dans sa revue = une nouvelle rubrique
2. il ajout le mot clef "Appel à participation"
3. il décrit ce qu'il attend dans ce numéro
4. il communique le lien vers cette rubrique pour proposer à son réseau de répondre à l'appel
5. dans la page de cette rubrique l'auteur intéressé clic sur un lien pour soumettre un article
6. l'auteur remplie le formulaire sans avoir à préciser ni la revue ni le numéro car nous le savons par le lien présent dans l'appel à participation

bénéfice : 
- permet de communiquer simplement le lien pour proposer un article
- plus simple pour l'auteur qui propose
- permet de mettre en route plusieurs numéros pour une même revue
- permet de lister tous les appels à proposition de toutes les revues

**Comment by ghislainguy** [comment]
On est d'accord, j'ai modifié le formulaire côté front, il est terminé ( sauf la vérification de la session utilisateur )
https://github.com/samszo/open-edition/blob/master/squelettes/form-article.html

Côté PHP et requête, je ne peux pas y toucher.

**Comment by samszo** [comment]
la page http://gapai.univ-paris8.fr/open-edition/spip.php?page=form-article
ne renvoie rien...
???

**Comment by samszo** [comment]
le téléchargement du pdf marche sur un article "publié" mais pas "en cours de rédaction"
c'est l'inverse qu'il faut...
une fois téléchargé la page n'affiche rien cf. http://gapai.univ-paris8.fr/open-edition/spip.php?page=form-article-pdf#formulaire_upload

**Comment by ghislainguy** [comment]
Si, normalement ça fonctionne sur les deux.

Il faut rajouter certain paramètres dans l'URL.  var_mode=preview pour les article qui ne sont pas publier.
Et id_article.

http://gapai.univ-paris8.fr/open-edition/spip.php?page=form-article-pdf&var_mode=preview&id_article=41

http://gapai.univ-paris8.fr/open-edition/spip.php?page=form-article-pdf&var_mode=preview&id_article=139

Edit : plus besoin de var_mode=preview
