### ISSUE TITLE
Bug du menu des Langues

### ISSUE THREAD

**Issue by ghislainguy** [samszo/open-edition#2]
Tout d'abbord il faudrait enlever le fichier mes_options.php 
car pour l'article ça ne fonctionne plus. je n'ai pas la permission dans le FTP pour le retirer.

Le vrai problème est que le menu des langues ne fonctionne que pour la page de l'article.
_English | français_

**Comment by samszo** [comment]
en fait il fallait lire la description du plugin langue préféré
j'ai changé sommaire.html et ajouté rubrique.html
Pour les domaines, il faudra faire un article dédié et le traduire.
Ensuite il faut faire une composition dédié à ces articles
