### ISSUE TITLE
Exports bibliographiques

### ISSUE THREAD

**Issue by ghislainguy** [samszo/open-edition#20]
Le plugin Cite n'est pas compatible...
ZotSpip également : 3.4.5 - stable version incompatible

Samuel, connais-tu le format .RIS ?
https://en.wikipedia.org/wiki/RIS_%28file_format%29

J'ai créé un squelette, qui peut générer une page comme celle-ci par exemple : 

```
AB  - [(#DESCRIPTIF|supprimer_tags)]<br>
DA  - #DATE<br>
DO  - #DOI<br>
ED  - Editor<br>
```

Par contre ça génère une page html, c'est pas un type de fichier spécifique à télécharger.
Cette solution serait la plus simple pour un export dans un format spécifique, si vous me donner un modèle, et si avec spip il est possible de générer un type de fichier spécifique.
J'ai essayer de trouver un plugin spip pour générer un fichier .ris (ou autre) à partir d'un squelette mais ça n'existe pas.

Tout ce que je peux proposer pour l'instant, c'est ce type de page :  http://gapai.univ-paris8.fr/open-edition/spip.php?page=ris&id_article=37
Ensuite il faut copier-coller.

J'ai aussi installé l'extension firefox Zotero. 
Je fais des tests : j'essaye d'intégrer des méta données dans la page de l'article, mais pour l'instant elles ne sont pas reconnues par Zotero.

**Comment by samszo** [comment]
j'ai installé le plugin http://contrib.spip.net/ZotSpip sur mon cite, il génère des références bibliographiques cf. http://www.samszo.univ-paris8.fr/spip.php?page=biblio + cliquer sur "Afficher/masquer les détails"
ce plugin utilise : https://bitbucket.org/rjerome/citeproc-php/
Voir comment fonctionne ZotSpip citeproc 

Pour l'exposition des metadata = rendre visible les metadata de l'article 
voir : https://www.zotero.org/support/dev/exposing_metadata
voir aussi le plugin http://contrib.spip.net/Dublin-Core
plus précisément cette page qui montre comment créer les metadata : http://zone.spip.org/trac/spip-zone/browser/_plugins_/dublin_core/trunk/dublin_core_article.html?rev=98048
il faut juste adapter cette page aux données et ajouter un include...

**Comment by ghislainguy** [comment]
J'avais essayer d'intaller ZotSpip, mais, il n'est pas encore compatible pour spip 3.1 http://contrib.spip.net/ZotSpip#forum485266

Que faire dans ce cas ?

**Comment by samszo** [comment]
1. mettre en place les metadata
2. utiliser citeproc-php sans ZotSpip

**Comment by ghislainguy** [comment]
Dublin core n'est pas compatible, je vais me servir de cette page, donc : http://zone.spip.org/trac/spip-zone/browser/_plugins_/dublin_core/trunk/dublin_core_article.html?rev=98048

**Comment by ghislainguy** [comment]
Pour l'export des fichier .RIS je suis arrivé à une solution, qui, je pense, fonctionne, j'ai besoin de vos avis.
Il y a un lien de téléchargement sur les articles.
Samuel, est-ce-que cette méthode peut servir pour les autres formats d'export ?
J'ai regardé l'exemple d'un export, en fichier texte et bibtex, pour ceux-là, je peux le faire.

J'ai utilisé #HTTP_HEADER dans un squelette pour générer les fichiers.

**Comment by ghislainguy** [comment]
Pouvez-vous me dire ce que vous pensez de l'export des articles en .RIS ?
Il manque certaines informations par exemple à la ligne JO, je ne sais pas trop quoi mettre à cette ligne par exemple.

**Comment by ghislainguy** [comment]
L'export en .RIS est terminé.

Edit : Tous les exports fonctionnent ! à vous de tester.
