### ISSUE TITLE
Listes des revues sur la page domaine

### ISSUE THREAD

**Issue by iste-max** [samszo/open-edition#26]
Peut-on avoir sur la page Domaine l’ensemble des revues, à la fois celles qui ont déjà un comité de rédaction, mais également celles qui sont à prévoir (et donc ne sont pas cliquable car les infos sur la revues ne sont pas complètes) ?

Cf : https://openscience.fr/homme-et-societe.html

**Comment by ghislainguy** [comment]
Oui c'est faisable : si je crée une deuxième boucle en dessous, avec les revues sans comité de rédaction. Je marquerais : revues à paraître.

**Comment by iste-max** [comment]
Parfait!

**Comment by ghislainguy** [comment]
ça marche. 
Si vous ne mettez aucun article dans la revue (y compris les le comité de redaction), elle s'affiche, mais sans lien, et avec le mot "à paraître"

Si vous mettez un article, la revue s'affiche comme d'habitude, avec un lien.
