### ISSUE TITLE
Erreur Formulaire de l'article

### ISSUE THREAD

**Issue by ghislainguy** [samszo/open-edition#28]
J'étais en train de finaliser le formulaire, je l'ai rendu accessible pour les auteurs connectés uniquement, et ça fonctionne. http://gapai.univ-paris8.fr/open-edition/numero-98

J'ai testé sur gapai, mais j'hésite à commit sur gitHub, car j'ai un nouveau problème : 

La création de l'article traduit ne fonctionne plus, et j'ai aussi un message d'erreur : 

Erreur : Récupère exception: Zend_Controller_Exception
Message: Invalid controller specified (error)#0 /var/www/Zend/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#1 /var/www/Zend/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#2 /var/www/Zend/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#3 /var/www/open-edition/admin/index.php(6): Zend_Application->run()
#4 {main}

**Comment by samszo** [comment]
il faudrait retourner directement au formulaire une fois connecté et pas dans l'espace privé

**Comment by samszo** [comment]
il manquait le paramètre "idRubNumTrad" dans le formulaire
