### ISSUE TITLE
La boucle des revues ABCD

### ISSUE THREAD

**Issue by ghislainguy** [samszo/open-edition#3]
Je n'y arrive pas avec la boucle qui génère le "tri  alphabétique"
c'est dans la page d'accueil sommaire.html
Je me suis servi de cette contribution pour commencer ma boucle :
http://contrib.spip.net/Tri-alphabetique-tout-en-SPIP

```
<BOUCLE_alpha2(DATA){enum A,Z}>
    #VALEUR

    <BOUCLE_revues(RUBRIQUES){lang=#LANG}{racine}>
        <BOUCLE_revues2(RUBRIQUES){id_parent}{par titre}>
        <p>#TITRE</p>
        </BOUCLE_revues2>
    </BOUCLE_revues>

</BOUCLE_alpha2>
```

**Comment by samszo** [comment]
tu n'avais pas mis la boucle qui génère les data.
tu n'as pas besoin de faire une première boucle sur la racine parce qu'elle est déjà fait à un niveau plus haut 
cf. https://github.com/samszo/open-edition/blob/master/squelettes/sommaire.html#L68

**Comment by ghislainguy** [comment]
Merci, ça fonctionne, j'ai aussi ajouter le système de lien en JS.
