### ISSUE TITLE
mise en page des titres sur la page article 

### ISSUE THREAD

**Issue by iste-max** [samszo/open-edition#37]
![second titre](https://cloud.githubusercontent.com/assets/17291882/16117439/02e51ec8-33ca-11e6-9280-d94b4edf971e.png)

mettre cette mise en page sur la page article (cf : pièce jointe « second titre », le second titre (le titre anglais quand le site est en Français) au-dessus de la ligne, un peu plus petit (peut-être 2pt inférieur) et dans un gris foncé. Pour faire en sorte qu’il soit moins imposant, car le titre anglais est plus une norme qu’un réel intérêt pour le lecteur.

**Comment by ghislainguy** [comment]
D'accord, il n'y aura plus que le titre Français et Anglais ? 
Vous n'allez pas avoir besoin des sous-titres Français/Anglais, en plus des titres ?

**Comment by ghislainguy** [comment]
C'est fait.
