### ISSUE TITLE
Page revue : Problème d'une boucle

### ISSUE THREAD

**Issue by ghislainguy** [samszo/open-edition#4]
http://gapai.univ-paris8.fr/open-edition/spip.php?page=revue&id_rubrique=4
Cette page est un bon exemple, il faut afficher les **Numéros de la revue** 
classer par volume et année.
Dans "*_2016 - Volume 2 *_" il y a : 
- numéro 1
- numéro 2
- numéro 3 etc.

"2016" est un mot clef, les numéros de volume "1" "2" "3" etc. en sont des autres.
Et je rapelle que les numéros sont des rubriques...

La boucle que j'ai faite affiche tous les mots "année" et pour chaque années, elle affiche tous les numéros correspondants. Le probème de ma boucle c'est qu'elle affiche même les années ou il n'y à pas de numéro !

PS : La boucle que j'ai faite ne gère pas les bon numéro de volume, j'utilise #COMPTEUR_BOUCLE je ne sais pas si c'est une bonne solution...

**Comment by samszo** [comment]
il faudrait que tu mettes un lien vers la ligne de code en question dans github

**Comment by ghislainguy** [comment]
http://gapai.univ-paris8.fr/open-edition/Ingenierie-cognitique
rubrique-revue.html  : ligne 99

```
<BOUCLE_motVol(MOTS){id_groupe=3}>
    <div class="block-num col-sm-4">
        <p>#TITRE - Volume #COMPTEUR_BOUCLE ?</p><br>
        <BOUCLE_num(RUBRIQUES){id_parent}{id_mot=#ID_MOT}>
            <a href="#URL_RUBRIQUE">#TITRE</a><br>
        </BOUCLE_num>
        <br>
    </div>
</BOUCLE_motVol>
```

Les fichiers à jours sont sur le serveur, 
merci...

**Comment by samszo** [comment]
le problème est régler en calculant des volume avec les 2 derniers chiffre de l'année et le numéro
cf. https://github.com/samszo/open-edition/blob/master/squelettes/compositions/rubrique-revue.html#L101

**Comment by ghislainguy** [comment]
ça fonctionne, je vais utiliser cette boucle sur la page "Article" et "Numéro".

**Comment by ghislainguy** [comment]
ça fonctionne dans toutes les pages, problème résolu.
