### ISSUE TITLE
L'appartenance des auteurs

### ISSUE THREAD

**Issue by ghislainguy** [samszo/open-edition#5]
Dans la page article, j'ai gérer les auteurs et leurs appartenance simplement : 
L'appartenance est enregistrée dans un champ extra pour chaque auteur.

Le problème est que l'article doit afficher l'appartenance au moment ou l'article à été écrit.
L'appartenance de l'auteur doit être enregistrer dans les articles.

Par exemple : Ghislain, "Paris8"
même si je change d'appartenance dans 2 ans, l'article doit toujours afficher "Paris8"

**Comment by samszo** [comment]
comme la saisie des articles se fera dans un formulaire externe, l'appartenance des auteurs se fera dans un champ dédié dont les valeurs seront conservées dans un des champs de l'article, par exemple : chapeau
