### ISSUE TITLE
Formulaire de proposition d'un article

### ISSUE THREAD

**Issue by ghislainguy** [samszo/open-edition#6]
Pour les auteurs, il faut un formulaire simple et clair pour qu'ils puissent proposer un article.

Une alternative au back-office, côté front.
Tout doit être sur la même page :  
- le champ du titre (français et anglais)
- le sous titre (français anglais)
- Le résumé  ( champ descriptif) (français anglais)
- le texte
- dans le texte il doit y avoir des titres **H2** (pour le sommaire)
- il doit y avoir des tableaux
- il doit y avoir des caractères spéciaux
- il peut y avoir des centaines d'images ( les formules seront gérer en image)
- notes de bas de page`[[avec la syntaxe de spip]]`
- les mots clefs de l'article ( français anglais )
- l'ajout des auteurs,  leurs appartenances et leurs email
- le champ DOI ?
- le choix des domaines et le domaine principal (champ extra)

Sachant que les auteurs travaillent avec word, et voudront faire un copier-coller.

**Comment by samszo** [comment]
on peut faire un formulaire de saisie qui prend en compte le copier coller word de ckeditor.
Par contre, pour les images, il faudra que l'auteur les téléchargent car elles sont sur sa machine et pas sur le serveur. Voir cet exemple de copier coller Word ici http://gapai.univ-paris8.fr/open-edition/ecrire/?exec=article_edit&id_article=16, et le code de l'image : 

<p>
    <img height="129" src="file://localhost/Users/samszo/Library/Caches/TemporaryItems/msoclip/0clip_image002.gif" width="342" /></p>

**Comment by ghislainguy** [comment]
Il faut aussi afficher les email des auteurs dans l'article.
Du coup le plus simple (maintenant) est d'enregistrer les emails dans l'article.

Voilà la page du formulaire : http://gapai.univ-paris8.fr/open-edition/spip.php?page=form-auteur&var_mode=calcul

**Comment by ghislainguy** [comment]
http://gapai.univ-paris8.fr/open-edition/spip.php?page=form-auteur
Est-il possible de rentrer un article dans spip, à partir de ce formulaire ? 
ce formulaire est idéal pour les auteurs.
L'idéal ça serais de créer un fichier php qui va faire toutes les requêtes SQL.

Sinon, on peux essayer de modifier le formulaire de spip.
J'ai fais un test : http://gapai.univ-paris8.fr/open-edition/spip.php?page=test
http://contrib.spip.net/Formulaire-d-ajout-modification-d-articles-cote-public
Mais je ne vois pas comment ajouter un champ,  le titre en anglais par exemple.

**Comment by samszo** [comment]
il faut prévoir un champ pour le corps de l'article en anglais

**Comment by samszo** [comment]
les auteurs peuvent mettre à jour leurs articles non encore publiés, il faut une page pour qu'ils puissent sélectionner ces articles

**Comment by ghislainguy** [comment]
Pour l'instant je n'arrive pas du tout à créer un formulaire fonctionnel*, d'habitude je fait tout simplement des requêtes SQL dans ma base. Sauf que là je ne sais pas comment faire.

*Un formulaire qui enregistre dans un article, ou n'importe ou, je veux dire.

**Comment by samszo** [comment]
tout est expliqué ici : http://programmer.spip.net/-Formulaires-35-

**Comment by ghislainguy** [comment]
Ils ne prévoient pas de traduire le corps des articles par contre, ce qui doit être traduit, ce sont le titre, sous-titre, mots-clefs et le résumé.

**Comment by samszo** [comment]
les articles ne seront pas tous en français mais parfois en anglais et même les deux comment tu fais la différence ?

**Comment by samszo** [comment]
j'ai mis en place une première version du formulaire : http://localhost/open-edition/spip.php?page=form-article
je n'utilise pas la mécanique de SPIP mais une API Zend : cf. https://github.com/samszo/open-edition/blob/master/application/controllers/CrudController.php#L6

il faut tester et voir si c'est plus efficace

**Comment by ghislainguy** [comment]
J'ai lu une bonne partie de la doc, que tu m'as envoyer, et j'ai compris le principe de base : 
http://gapai.univ-paris8.fr/open-edition/spip.php?page=test2&var_mode=calcul
Maintenant je vais voir pour savoir comment faire les requêtes dans la base.

**Comment by ghislainguy** [comment]
Je suis en train de mettre àjour le formulaire,
Après, j'aimerais savoir comment le formulaire enregistre les infos dans la base. Je ne trouve pas le fichier PHP qui fait les requêtes...
