### ISSUE TITLE
Devons-nous utiliser le Plugin Compositions ?

### ISSUE THREAD

**Issue by ghislainguy** [samszo/open-edition#8]
On a des revues et des numéros, qui sont des rubriques ayant un champ extra "type de rubrique" (numéro, numéro spécial, revue ou rien) 

Pour l'instant pour la mise en page des pages "revue" ou "numéro" j'utilise les pages numéro.html et revue.html, classique dans le fonctionnement de spip...

Mais l'inconvéniant c'est les url : http://gapai.univ-paris8.fr/open-edition/spip.php?page=revue&id_rubrique=4

J'ai essayer d'utiliser ce plugin mais, je n'arrive pas à définir comment une rubrique avec un champ extra de type revue doit utiliser le squelette revue. ça me semble trop difficile finalement d'utiliser le plugin...
et je ne sais pas si ça résoudra le problème.

**Comment by samszo** [comment]
Pour les compositions il faut un xml + un squelette
Dans le répertoire compositions tu avais oublié le squelette.
Je l'ai mis et on peut voir maintenant la composition ici : http://gapai.univ-paris8.fr/open-edition/ecrire/?exec=compositions
L'application d'une composition à une rubrique ou un article se fait dans l'interface privée en précisant si on prend une autre composition que celle par défaut cf. http://gapai.univ-paris8.fr/open-edition/ecrire/?exec=rubrique&id_rubrique=10
et le résultat avec la réécriture d'url =  http://gapai.univ-paris8.fr/open-edition/Revue-B

**Comment by ghislainguy** [comment]
J'ai compris, c'est au moment de la creation de la rubrique qu'il faut préciser la composition.
Merci.

**Comment by ghislainguy** [comment]
http://gapai.univ-paris8.fr/open-edition/Une-revue
ça à l'air de fonctionner super, en plus la gestion des langue fonctionne sur cette page maintenant.

**Comment by ghislainguy** [comment]
Par contre je n'ai plus le droit d'accès  pour le fichier rubrique-revue.html...

**Comment by ghislainguy** [comment]
Pour les mots-clefs, le choix de la composition n'apparait pas. ( mot-domaine.html )
