### ISSUE TITLE
Plugin composition Et page mot-clefs

### ISSUE THREAD

**Issue by ghislainguy** [samszo/open-edition#9]
J'ai fait un squelette mot-domaine.html + le xml dans le dossier compositions.
Il est reconnu par le plugin http://gapai.univ-paris8.fr/open-edition/ecrire/?exec=compositions
mais impossible d'associer ni un groupe de mot ni un mot clef à ce squelette.

**Comment by ghislainguy** [comment]
J'ai créé un article "domaines" et je lui ai assigné une composition, ça marche mais lorsqu'on change de langue, le paramètre n'est pas conserver : http://gapai.univ-paris8.fr/open-edition/Domaines?id_mot=6 
et l'url n'est pas très propre... (réécriture d'url + un paramètre )

J'ai finalement dépublier les articles "domaines" (et la version anglaise) car sinon l'accueil ne fonctionne plus.
Pour corriger ça j'ai essayer d'appliquer une composition à la rubrique pour l'accueil, mais ça reviens au même.
Je cherche...

**Comment by samszo** [comment]
Pour avoir une gestion optimum des pages de domaine il faut créer un article par domaine et le traduire dans la langue cf. http://gapai.univ-paris8.fr/open-edition/domaine_Mathematiques-et-statistiques

**Comment by samszo** [comment]
j'ai modifié https://github.com/samszo/open-edition/blob/master/squelettes/inclure/domaines-nav.html
pour que le menu de gauche se base sur la nouvelle configuration

**Comment by samszo** [comment]
j'ai mis à jour la page du sommaire pour prendre en compte les modifications...

**Comment by ghislainguy** [comment]
J'ai vue mais le menu de gauche ne fonctionne pas sur toutes les autres pages, je vais regarder ça.
sur la boucle <BOUCLE_menuDom(ARTICLES)  il y a un critère :   {id_rubrique} 
je l'ai enlever, ça fonctionne maintenant.

**Comment by ghislainguy** [comment]
Problème résolu !
